import { Product, SaleRecord, User, AppSetting } from './types';

export const MOCK_USERS: User[] = [
  { id: '1', name: 'Admin User', email: 'admin@epos.com', role: 'admin', status: 'active' },
  { id: '2', name: 'Dr. Sarah', email: 'pharm@epos.com', role: 'pharmacist', status: 'active' },
  { id: '3', name: 'Ali Cashier', email: 'cash@epos.com', role: 'cashier', status: 'active' },
];

export const DEFAULT_SETTINGS: AppSetting[] = [
  // General Store Settings
  { id: 1, key: 'store_name', value: 'EPOS Pharma', description: 'Name of the pharmacy', group: 'general' },
  { id: 2, key: 'store_address', value: '123 Medical Road, Lahore', description: 'Full address', group: 'general' },
  { id: 3, key: 'store_phone', value: '+92 300 1234567', description: 'Contact number', group: 'general' },
  { id: 4, key: 'store_email', value: 'contact@epospharma.com', description: 'Contact email', group: 'general' },
  { id: 5, key: 'pharmacy_license', value: 'PH-LHR-09821', description: 'Legal License Number', group: 'general' },
  { id: 6, key: 'currency_symbol', value: 'PKR', description: 'Currency symbol displayed', group: 'general' },
  { id: 7, key: 'store_logo', value: '', description: 'URL or Path to Logo', group: 'general' },

  // Inventory & Alerts
  { id: 10, key: 'expiry_alert_days', value: '90', description: 'Days before expiry to alert', group: 'inventory' },
  { id: 11, key: 'low_stock_limit_default', value: '5', description: 'Default low stock threshold', group: 'inventory' },
  { id: 12, key: 'default_markup_percent', value: '20', description: 'Default profit margin %', group: 'inventory' },

  // Billing
  { id: 20, key: 'tax_rate', value: '0', description: 'Global Tax/VAT %', group: 'billing' },
  { id: 21, key: 'receipt_footer', value: 'Get well soon!\nNo returns after 3 days without receipt.', description: 'Message on receipt bottom', group: 'billing' },
  { id: 22, key: 'printer_type', value: 'thermal_80', description: 'Printer format code', group: 'billing' },
  { id: 23, key: 'auto_print', value: 'true', description: 'Auto print after sale', group: 'billing' },
];

export const MOCK_PRODUCTS: Product[] = [
  { 
    id: 1, 
    name: "Amoxil", 
    genericName: "Amoxicillin", 
    strength: "500mg", 
    form: "Capsule", 
    category: "Antibiotics", 
    price: 350, 
    costPrice: 280,
    stock: 145, 
    expiryDate: "2025-12-01", 
    barcode: "MED892301", 
    sku: "AMX-500-CAP",
    batchNumber: "BX-2023-001",
    supplier: "GSK",
    packSize: "Box of 20",
    reorderLevel: 20,
    location: "Rack A-1",
    requiresPrescription: true,
    isNarcotic: false
  },
  { 
    id: 2, 
    name: "Panadol Advance", 
    genericName: "Paracetamol", 
    strength: "500mg", 
    form: "Tablet", 
    category: "Pain Relief", 
    price: 45, 
    costPrice: 35,
    stock: 500, 
    expiryDate: "2026-05-15", 
    barcode: "MED827361", 
    sku: "PAN-500-TAB",
    batchNumber: "BX-2023-099",
    supplier: "GSK",
    packSize: "Strip of 10",
    reorderLevel: 50,
    location: "Rack B-2",
    requiresPrescription: false,
    isNarcotic: false
  },
  { 
    id: 3, 
    name: "Brufen", 
    genericName: "Ibuprofen", 
    strength: "400mg", 
    form: "Tablet", 
    category: "Pain Relief", 
    price: 85, 
    costPrice: 65,
    stock: 32, 
    expiryDate: "2024-11-20", 
    barcode: "MED102938", 
    sku: "BRU-400-TAB",
    batchNumber: "BR-998-A",
    supplier: "Abbott",
    packSize: "Box of 50",
    reorderLevel: 10,
    location: "Rack B-3",
    requiresPrescription: false,
    isNarcotic: false
  },
  { 
    id: 4, 
    name: "Centrum Silver", 
    genericName: "Multivitamins", 
    strength: "Standard", 
    form: "Tablet", 
    category: "Vitamins", 
    price: 2500, 
    costPrice: 2100,
    stock: 80, 
    expiryDate: "2025-08-10", 
    barcode: "MED554433", 
    sku: "CEN-SLV-TAB",
    batchNumber: "IMP-221",
    supplier: "Pfizer",
    packSize: "Bottle of 60",
    reorderLevel: 5,
    location: "Shelf C",
    requiresPrescription: false,
    isNarcotic: false
  },
  { 
    id: 5, 
    name: "Augmentin", 
    genericName: "Amoxicillin/Clavulanate", 
    strength: "1g", 
    form: "Tablet", 
    category: "Antibiotics", 
    price: 450, 
    costPrice: 380,
    stock: 12, 
    expiryDate: "2024-10-01", 
    barcode: "MED998877", 
    sku: "AUG-1G-TAB",
    batchNumber: "AUG-X12",
    supplier: "GSK",
    packSize: "Box of 6",
    reorderLevel: 15,
    location: "Rack A-1",
    requiresPrescription: true,
    isNarcotic: false
  },
  { 
    id: 6, 
    name: "SunnyPlast", 
    genericName: "Adhesive Bandages", 
    strength: "N/A", 
    form: "Sachet", 
    category: "First Aid", 
    price: 50, 
    costPrice: 30,
    stock: 200, 
    expiryDate: "2028-01-01", 
    barcode: "MED112233", 
    sku: "BAN-BOX-STD",
    batchNumber: "NA",
    supplier: "Local",
    packSize: "Box of 100",
    reorderLevel: 20,
    location: "Counter",
    requiresPrescription: false,
    isNarcotic: false
  },
  { 
    id: 7, 
    name: "Glucophage", 
    genericName: "Metformin", 
    strength: "500mg", 
    form: "Tablet", 
    category: "Chronic Care", 
    price: 210, 
    costPrice: 180,
    stock: 300, 
    expiryDate: "2025-03-20", 
    barcode: "MED445566", 
    sku: "GLU-500-TAB",
    batchNumber: "MTF-001",
    supplier: "Merck",
    packSize: "Box of 50",
    reorderLevel: 30,
    location: "Rack D-1",
    requiresPrescription: true,
    isNarcotic: false
  },
  { 
    id: 8, 
    name: "Lipitor", 
    genericName: "Atorvastatin", 
    strength: "20mg", 
    form: "Tablet", 
    category: "Chronic Care", 
    price: 950, 
    costPrice: 850,
    stock: 45, 
    expiryDate: "2025-06-15", 
    barcode: "MED778899", 
    sku: "LIP-20-TAB",
    batchNumber: "LIP-999",
    supplier: "Pfizer",
    packSize: "Box of 30",
    reorderLevel: 10,
    location: "Rack D-2",
    requiresPrescription: true,
    isNarcotic: false
  },
  { 
    id: 9, 
    name: "Cebosh", 
    genericName: "Vitamin C", 
    strength: "1000mg", 
    form: "Tablet", 
    category: "Vitamins", 
    price: 400, 
    costPrice: 320,
    stock: 150, 
    expiryDate: "2026-02-28", 
    barcode: "MED332211", 
    sku: "VIT-C-1000",
    batchNumber: "VIT-2023",
    supplier: "Getz",
    packSize: "Tube of 20",
    reorderLevel: 20,
    location: "Counter",
    requiresPrescription: false,
    isNarcotic: false
  },
  { 
    id: 10, 
    name: "Xanax", 
    genericName: "Alprazolam", 
    strength: "0.5mg", 
    form: "Tablet", 
    category: "Psychiatry", 
    price: 200, 
    costPrice: 150,
    stock: 100, 
    expiryDate: "2025-09-10", 
    barcode: "MED665544", 
    sku: "XAN-05-TAB",
    batchNumber: "XAN-001",
    supplier: "Pfizer",
    packSize: "Box of 30",
    reorderLevel: 10,
    location: "Safe Locker",
    requiresPrescription: true,
    isNarcotic: true
  },
];

export const REVENUE_DATA: SaleRecord[] = [
  { date: 'Mon', amount: 12000 },
  { date: 'Tue', amount: 14500 },
  { date: 'Wed', amount: 11000 },
  { date: 'Thu', amount: 17500 },
  { date: 'Fri', amount: 21000 },
  { date: 'Sat', amount: 19000 },
  { date: 'Sun', amount: 9500 },
];

export const CATEGORY_DATA = [
  { name: 'Antibiotics', value: 35 },
  { name: 'Pain Relief', value: 25 },
  { name: 'Chronic Care', value: 20 },
  { name: 'Vitamins', value: 15 },
  { name: 'First Aid', value: 5 },
];